---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubtu18cis_autofs_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes
  when:
      - ubtu18cis_rule_1_4_1

- name: "PRELIM | Check for avahi-daemon service"
  shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for cups service"
  shell: "systemctl show cups | grep LoadState | cut -d = -f 2"
  register: cups_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for dhcpd service"
  shell: "systemctl show isc-dhcp-server | grep LoadState | cut -d = -f 2"
  register: dhcp_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for dhcp6 service"
  shell: "systemctl show isc-dhcp-server6 | grep LoadState | cut -d = -f 2"
  register: dhcp6_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Check for slapd service"
  shell: "systemctl show slapd | grep LoadState | cut -d = -f 2"
  register: slapd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint