---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubtu18cis_autofs_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint

- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes
  when:
      - ubtu18cis_rule_1_4_1