---
- name: "NOTSCORED | 6.1.1 | AUDIT | Audit system file permissions"
  block:
      - name: "NOTSCORED | 6.1.1 | AUDIT | Audit system file permissions | Register package list"
        command: ls -a /bin/
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_1_packages

      # - name: "NOTSCORED | 6.1.1 | AUDIT | Audit system file permissions | Audit the packages"
      #   command: dpkg --verify {{ item }}
      #   changed_when: false
      #   failed_when: false
      #   with_items:
      #       - "{{ ubtu18cis_6_1_1_packages.stdout_lines }}"
      #   register: ubtu18cis_6_1_1_packages_audited

      - name: "NOTSCORED | 6.1.1 | AUDIT | Audit system file permissions | Message out packages results for review"
        debug:
            msg:
                - "ALERT!!!! Below are the packages that need to be reviewed."
                - "You can run dpkg --verify <package name> and if nothing is returned the package is installed correctly"
                - "{{ ubtu18cis_6_1_1_packages.stdout_lines }}"
  when:
      - ubtu18cis_rule_6_1_1
  tags:
      - level2-server
      - level2-workstation
      - notscored
      - audit
      - rule_6.1.1
      - permissions

- name: "SCORED | 6.1.2 | PATCH | Ensure permissions on /etc/passwd are configured"
  file:
      path: /etc/passwd
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.2
      - permissions

- name: "SCORED | 6.1.3 | PATCH | Ensure permissions on /etc/gshadow- are configured"
  file:
      path: /etc/gshadow-
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.3
      - permissions

- name: "SCORED | 6.1.4 | PATCH | Ensure permissions on /etc/shadow are configured"
  file:
      path: /etc/shadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.4
      - permissions

- name: "SCORED | 6.1.5 | PATCH | Ensure permissions on /etc/group are configured"
  file:
      path: /etc/group
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.5
      - permissions

- name: "SCORED | 6.1.6 | PATCH | Ensure permissions on /etc/passwd- are configured"
  file:
      path: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_6
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.6
      - permissions

- name: "SCORED | 6.1.7 | PATCH | Ensure permissions on /etc/shadow- are configured"
  file:
      path: /etc/shadow-
      owner: root
      group: shadow
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_7
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.7
      - permissions

- name: "SCORED | 6.1.8 | PATCH | Ensure permissions on /etc/group- are configured"
  file:
      path: /etc/group-
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_8
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.8
      - permissions

- name: "SCORED | 6.1.9 | PATCH | Ensure permissions on /etc/gshadow are configured"
  file:
      path: /etc/gshadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_9
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.9
      - permissions

- name: "SCORED | 6.1.10 | PATCH | Ensure no world writable files exist"
  block:
      - name: "SCORED | 6.1.10 | PATCH | Ensure no world writable files exist | Get list of world-writable files"
        shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type f -perm -0002
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_10_wwf

      - name: "SCORED | 6.1.10 | PATCH | Ensure no world writable files exist | Adjust world-writable files if they exist"
        file:
            path: "{{ item }}"
            mode: o-w
        with_items:
            - "{{ ubtu18cis_6_1_10_wwf.stdout_lines }}"
        when:
            - ubtu18cis_no_world_write_adjust
  when:
      - ubtu18cis_rule_6_1_10
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_6.1.10
      - permissions