---
- name: "SCORED | 3.1.1 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  notify: sysctl flush ipv4 route table
  when:
      - ubtu18cis_rule_3_1_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_3.1.1
      - packet_redirect