---
- name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
  service:
      name: cron
      enabled: yes
  when:
      - ubtu18cis_rule_5_1_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.1
      - cron

- name: "SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
      path: /etc/crontab
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_5_1_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.2
      - cron

- name: "SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
      path: /etc/cron.hourly
      owner: root
      group: root
      mode: 0700
  when:
      - ubtu18cis_rule_5_1_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.3
      - cron

- name: "SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
      path: /etc/cron.daily
      owner: root
      group: root
      mode: 0700
  when:
      - ubtu18cis_rule_5_1_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.4
      - cron

- name: "SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
      path: /etc/cron.weekly
      owner: root
      group: root
      mode: 0700
  when:
      - ubtu18cis_rule_5_1_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.5
      - cron

- name: "SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
      path: /etc/cron.monthly
      owner: root
      group: root
      mode: 0700
  when:
      - ubtu18cis_rule_5_1_6
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.6
      - cron

- name: "SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
      path: /etc/cron.d
      owner: root
      group: root
      mode: 0700
  when:
      - ubtu18cis_rule_5_1_7
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.7
      - cron

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  block:
      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users | Remove deny configs"
        file:
            path: "{{ item }}"
            state: absent
        with_items:
            - /etc/at.deny
            - /etc/cron.deny

      - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users | Create allow files"
        file:
            path: "{{ item }}"
            owner: root
            group: root
            mode: 0640
            state: touch
        with_items:
            - /etc/cron.allow
            - /etc/at.allow
  when:
      - ubtu18cis_rule_5_1_8
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.1.8
      - cron

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      path: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_5_2_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.1
      - ssh

- name: "SCORED | 5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
      - name: "SCORED | 5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured | Find ssh_host private keys"
        find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key'
        register: ubtu18cis_5_2_2_ssh_host_priv_keys

      - name: "SCORED | 5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured | Set permissions"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        with_items:
            - "{{ ubtu18cis_5_2_2_ssh_host_priv_keys.files }}"
  when:
      - ubtu18cis_rule_5_2_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.2
      - ssh

- name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
      - name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured | Find ssh_host public keys"
        find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key.pub'
        register: ubtu18cis_5_2_3_ssh_host_pub_keys
      - debug: var=ubtu18cis_5_2_3_ssh_host_pub_keys
      - name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured | Set permissions"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0644
        with_items:
            - "{{ ubtu18cis_5_2_3_ssh_host_pub_keys.files }}"
  when:
      - ubtu18cis_rule_5_2_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.3
      - ssh

# -------------
# -------------
# Protocol command no longer exists in newer versions of sssh (7.4+). However adding it will not cause issues
# -------------
# -------------
- name: "SCORED | 5.2.4 | PATCH | Ensure SSH Protocol is not set to 1"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Protocol|^#Protocol'
      line: 'Protocol 2'
  when:
      - ubtu18cis_rule_5_2_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.4
      - ssh

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^LogLevel|^#LogLevel'
      line: 'LogLevel {{ ubtu18cis_log_level }}'
      insertafter: '^# Logging'
  when:
      - ubtu18cis_rule_5_2_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.5
      - ssh

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^X11Forwarding|^#X11Forwarding'
      line: 'X11Forwarding no'
  when:
      - ubtu18cis_rule_5_2_6
  tags:
      - leve2-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.6
      - ssh

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxAuthTries|^#MaxAuthTries'
      line: 'MaxAuthTries {{ ubtu18cis_max_auth_tries }}'
  when:
      - ubtu18cis_rule_5_2_7
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.7
      - ssh

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts|^#IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  when:
      - ubtu18cis_rule_5_2_8
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.8
      - ssh

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication|^#HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  when:
      - ubtu18cis_rule_5_2_9
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.9
      - ssh

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin|^#PermitRootLogin'
      line: 'PermitRootLogin no'
  when:
      - ubtu18cis_rule_5_2_10
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.10
      - ssh

- name: "SCORED | 5.2.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords|^#PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      insertafter: '# To disable tunneled clear text passwords'
  when:
      - ubtu18cis_rule_5_2_11
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.11
      - ssh

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment|^#PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  when:
      - ubtu18cis_rule_5_2_12
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.2.12
      - ssh