---
- name: grub update
  command: update-grub
  failed_when: false

- name: restart postfix
  service:
      name: postfix
      state: restarted

- name: sysctl flush ipv4 route table
  sysctl:
      name: net.ipv4.route.flush
      value: '1'
      sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
      name: net.ipv6.route.flush
      value: '1'
      sysctl_set: yes
  when: ansible_virtualization_type != "docker"